### PR TITLE
[readme] Update path of generate_templates

### PR DESCRIPTION
**Pull request by goldyfruit**
`./scripts/generate_templates.sh` doesn't exist anymore and
seems have been replaced by a Python script under the root
directory.

### CODE REVIEW

**Comment by tylert** [comment]
@goldyfruit thanks for the PR but I notice that your commit to update the readme was followed by another commit that isn't a readme change.  Could you please update this branch to only include the readme change?

Also, it would seem that the qemuargs change you are proposing here would only work for people who had that exact same `/usr/share/ovmf/OVMF.fd` file on their system.  I'm guessing this might have simply been an accidental commit on your feature branch.

**Comment by tylert** [comment]
@goldyfruit J'aimerai mieux qu'on n'ajoute pas l'autre commit avec tout les changements pour le "bios".

**Comment by goldyfruit** [comment]
> @goldyfruit J'aimerai mieux qu'on n'ajoute pas l'autre commit avec tout les changements pour le "bios".
Sorry about that, I reverted the commit.

**Comment by tylert** [comment]
Please squash your commits to remove the intermediate fluff (https://linuxhint.com/how-to-squash-git-commits/;  https://jamescooke.info/git-to-squash-or-not-to-squash.html).

**Comment by tylert** [comment]
Closing this PR.

**Pull request closed without merging**
